Juego Wordle
open-source-uc/introgames-contrib pull request #3
Opened 2022-08-30 01:49 UTC by MiraiAlam

2022-09-02 18:04 UTC, fernandosmither requested changes
Hola @MiraiAlam ! Muchas gracias por tu aporte 😄. Sin embargo, para poder aceptar tu Pull Request necesitaré que hagas un cambio chico 🤓.

1. Crea una nueva carpeta con tu usuario de GitHub, y dentro de esa una que se llame `Wordle`
2. Mueve los archivos de juego `PlayWordleES.py`, `WordleESprep.py` y `castellano.txt` dentro de la carpeta `Wordle`
3. Haz git push para que se actualice esta Pull Request (Es cierto, no necesitas crear otra PR para hacer cambios!)

Luego de eso, quedará aprobada tu contribución. Cualquier duda por favor escríbela aquí o háblame por Telegram ([@fdsmith](t.me/fdsmith)).

2022-09-06 17:02 UTC, MiraiAlam commented
holaa!! estoy intentando hacer el git push pero me tira un error (403), no se como arreglarlo 
<img width="918" alt="Screen Shot 2022-09-06 at 13 01 38" src="https://user-images.githubusercontent.com/103217936/188696557-6c2ae25d-160f-4f9f-b354-d6f94617db9a.png">

2022-09-06 23:46 UTC, fernandosmither commented
Holaa! Que bacán que estés aportando 👍 

Si te das cuenta, estás intentando hacer push directo a este repositorio, y no a la copia tuya, al _fork_ que hiciste, que es donde deberías hacer el push.
![image](https://user-images.githubusercontent.com/66154723/188758898-5ca33c5d-8427-4275-a9b5-26d74d8040f8.png)

Al repositorio que debes hacerle tus cambios es el tuyo personal. Es decir, [https://github.com/MiraiAlam/introgames-contrib](https://github.com/MiraiAlam/introgames-contrib)

Me imagino que esa carpeta es la que descargaste directamente desde aquí. Si no tienes otra carpeta, puedes simplemente clonar de nuevo tu repositorio (no este) y pushear los cambios. ¡Avísame cualquier cosa! 😄

2022-09-07 00:37 UTC, MiraiAlam commented
ahi lo logre!! muchas gracias!!

2022-09-07 01:59 UTC, fernandosmither approved these changes

2022-09-07 01:59 UTC, merged